/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './fixedscroll.module';
class NgFixedScrollModuleInjector extends import0.ɵNgModuleInjector<import1.NgFixedScrollModule> {
  _NgFixedScrollModule_0:import1.NgFixedScrollModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.NgFixedScrollModule {
    this._NgFixedScrollModule_0 = new import1.NgFixedScrollModule();
    return this._NgFixedScrollModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.NgFixedScrollModule)) { return this._NgFixedScrollModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgFixedScrollModuleNgFactory:import0.NgModuleFactory<import1.NgFixedScrollModule> = new import0.NgModuleFactory<any>(NgFixedScrollModuleInjector,import1.NgFixedScrollModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21udC9nL1Byb2pldG9zL0JhcmF0by9Jb25pY1Byb2plY3RzL0lvbmljMi1DYWxlbmRhci9zcmMvZml4ZWRzY3JvbGwubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL21udC9nL1Byb2pldG9zL0JhcmF0by9Jb25pY1Byb2plY3RzL0lvbmljMi1DYWxlbmRhci9zcmMvZml4ZWRzY3JvbGwubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
